### PR TITLE
SalesforceIQ Adapter Listing

### PR DESCRIPTION
**Pull request by njyjn**
Requested by @svchandra for #90

### CODE REVIEW

**Comment by svchandra** [comment]
@bryanyap can you update this listing page.

**Comment by bryanyap** [comment]
@svchandra can you add the connector url here?

**Comment by svchandra** [comment]
@bryanyap 
+      "name":"SalesforceIQ",
+      "image":"images/salesforceiq.png",
+      "link":"https://www.workato.com/custom_adapters/1747?token=457560e5"

**Comment by bryanyap** [comment]
@svchandra updates have been made.

**Pull request merged**
